language: node_js

node_js:
  - "8"
  - "6"
  - "4"
  - "0.12"

cache:
  directories:
    - node_modules

# Prevent Node 0.12 from installing the latest NPM as it is not compatible
install:
  - |
    if [ $(node -e "var major = process.version.replace(/^v?(\d+)\..+$/, '$1'); process.exit(parseInt(major, 10) !== 0 ? 0 : 1);") ]; then
      npm install -g npm@latest
    fi
  - npm install

script:
  - npm test
  - npm run build

sudo: false
